# .github/workflows/ci.yml
name: CI Workflow

# 當有 push 到 main 分支時就會觸發此工作流程
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # 指定使用自架構 Runner 執行
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Display a hello message
        run: echo "Hello, this job is running on my self-hosted runner!"
        
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"