# .github/workflows/ci.yml
name: CI Workflow

permissions:
  contents: read 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Display a hello message
        run: echo "Hello, this job is running on my self-hosted runner!"
        
      - name: Build the site in the jekyll/builder container
        shell: bash 
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"